[en]
  languageName = "English"
  contentDir = "content"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://thoreinstein.github.io/aix/">aix</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/docs/getting-started/">aix v1.0 just shipped!</a>'
